export type Locale = "ru" | "ro";
export const defaultLocale: Locale = "ru";
export function normalizeLocale(value?: string | null): Locale { return value === "ro" ? "ro" : "ru"; }

export const dictionaries = {
  ru: {
    home:"Главная", search:"Поиск", find:"Найти", apply:"Показать товары", allMoldova:"Вся Молдова", city:"Город", store:"Магазин", allStores:"Все магазины", sortCheap:"Сначала дешевле", sortExpensive:"Сначала дороже", sortNearest:"Сначала ближайшие", searchPlaceholder:"Найти товар в магазинах Молдовы", heroTitle:"Найдите лучшую цену рядом", heroText:"Один товар — все актуальные цены, наличие и ближайшие магазины Молдовы.", heroPlaceholder:"Помидоры, iPhone или штукатурка", stores:"магазинов", products:"товаров", offers:"предложений", categories:"Категории", popularOffers:"Выгодные предложения", popularOffersText:"Сравните цены разных магазинов и выберите подходящее предложение.", noImage:"Нет изображения", noCategory:"Без категории", from:"от", offersShort:"предлож.", inStock:"в наличии", noOffers:"Предложений пока нет", compareOffers:"Сравнить цены", searchAllProducts:"все товары", results:"результатов", demoData:"демо-данные", localStockUnknown:"филиал есть, локальный остаток не подтверждён", toStore:"На сайт магазина ↗", priceSource:"Источник цены ↗", openCompare:"Все предложения →", nothingFound:"Ничего не найдено для выбранных условий.", categoryNotFound:"Категория не найдена.", bestPrice:"Минимальная цена", confirmedStock:"с подтверждённым наличием", noCurrentOffers:"Нет актуальных предложений", specifications:"Характеристики", storeOffers:"Цены в магазинах", offerExplanation:"Показываем только актуальные предложения. Наличие филиала отмечаем отдельно, когда магазин раскрывает эти данные.", availableInBranches:"Доступно в {available} из {total} проверенных филиалов", branchStockUnknown:"магазин присутствует, остаток филиала не подтверждён", outOfStock:"Нет в наличии", preorder:"Предзаказ", inStockExact:"В наличии · {quantity} шт.", inStockLabel:"В наличии", stockUnknown:"Наличие уточняется", itemsInCategory:"товаров", goodsInCity:"Товары в {city}", language:"Язык", useLocation:"Найти рядом со мной", locating:"Определяем местоположение…", locationReady:"Ищем рядом", locationError:"Не удалось получить геолокацию", clearLocation:"Сбросить местоположение", radius:"Радиус", nearestStore:"Ближайший магазин", distanceAway:"{distance} км", previousPage:"← Назад", nextPage:"Далее →", pageOf:"Страница {page} из {pages}", filters:"Фильтры", price:"Цена, MDL", priceFrom:"От", priceTo:"До", brandLabel:"Бренд", allBrands:"Все бренды", catalog:"Каталог", nearby:"Рядом", resetFilters:"Сбросить", trustedData:"Актуальные цены", trustedDataText:"Устаревшие предложения автоматически скрываются из сравнения.", externalCheckout:"Прямая карточка товара открывается, когда магазин её предоставляет; брошюра отдельно отмечена как источник цены.",
    openNow:"Открыто сейчас", closedNow:"Закрыто сейчас", todayHours:"сегодня", hoursUnknown:"Часы работы не указаны", onlineOnly:"Только онлайн", temporarilyClosed:"Временно закрыто",
    account:"Личный кабинет", signIn:"Войти", signOut:"Выйти", signInTitle:"Вход в Moldova Commerce", signInText:"Войдите через OAuth, чтобы хранить бонусные карты и пользоваться ими с любого устройства.", continueGoogle:"Продолжить с Google", continueGithub:"Продолжить с GitHub", oauthPrivacy:"Мы не храним пароль от Google или GitHub. Авторизация выполняется у выбранного провайдера.", myCards:"Мои бонусные карты", cardsIntro:"Все карты магазинов в одном месте — покажите штрихкод или QR-код на кассе.", addCard:"Добавить карту", addCardHint:"Введите данные с физической карты или из приложения магазина. Сканирование камерой добавим следующим этапом.", cardLabel:"Название карты / магазина", cardholderName:"Имя владельца (необязательно)", cardCode:"Номер или содержимое QR/штрихкода", cardNotes:"Заметка (необязательно)", favorite:"Избранная карта", saveCard:"Сохранить карту", deleteCard:"Удалить карту", noCards:"У вас пока нет сохранённых карт.", cardSecurity:"Код карты шифруется перед записью в PostgreSQL. Для production настройте отдельный LOYALTY_CARD_ENCRYPTION_KEY.", points:"бонусов"
  },
  ro: {
    home:"Acasă", search:"Căutare", find:"Caută", apply:"Arată produsele", allMoldova:"Toată Moldova", city:"Oraș", store:"Magazin", allStores:"Toate magazinele", sortCheap:"Mai întâi ieftine", sortExpensive:"Mai întâi scumpe", sortNearest:"Cele mai apropiate", searchPlaceholder:"Caută un produs în magazinele din Moldova", heroTitle:"Găsește cel mai bun preț aproape", heroText:"Un produs — toate prețurile actuale, stocul și magazinele apropiate din Moldova.", heroPlaceholder:"Roșii, iPhone sau tencuială", stores:"magazine", products:"produse", offers:"oferte", categories:"Categorii", popularOffers:"Oferte avantajoase", popularOffersText:"Compară prețurile magazinelor și alege oferta potrivită.", noImage:"Fără imagine", noCategory:"Fără categorie", from:"de la", offersShort:"oferte", inStock:"în stoc", noOffers:"Nu există încă oferte", compareOffers:"Compară prețurile", searchAllProducts:"toate produsele", results:"rezultate", demoData:"date demo", localStockUnknown:"magazinul există aici, stocul local nu este confirmat", toStore:"Site-ul magazinului ↗", priceSource:"Sursa prețului ↗", openCompare:"Toate ofertele →", nothingFound:"Nu s-a găsit nimic pentru condițiile selectate.", categoryNotFound:"Categoria nu a fost găsită.", bestPrice:"Preț minim", confirmedStock:"cu stoc confirmat", noCurrentOffers:"Nu există oferte actuale", specifications:"Caracteristici", storeOffers:"Prețuri în magazine", offerExplanation:"Afișăm doar ofertele actuale. Marcăm stocul filialei separat atunci când magazinul oferă aceste date.", availableInBranches:"Disponibil în {available} din {total} filiale verificate", branchStockUnknown:"magazinul este prezent, stocul filialei nu este confirmat", outOfStock:"Nu este în stoc", preorder:"Precomandă", inStockExact:"În stoc · {quantity} buc.", inStockLabel:"În stoc", stockUnknown:"Disponibilitatea se verifică", itemsInCategory:"produse", goodsInCity:"Produse în {city}", language:"Limba", useLocation:"Caută lângă mine", locating:"Determinăm locația…", locationReady:"Căutăm în apropiere", locationError:"Nu am putut obține geolocația", clearLocation:"Șterge locația", radius:"Rază", nearestStore:"Cel mai apropiat magazin", distanceAway:"{distance} km", previousPage:"← Înapoi", nextPage:"Înainte →", pageOf:"Pagina {page} din {pages}", filters:"Filtre", price:"Preț, MDL", priceFrom:"De la", priceTo:"Până la", brandLabel:"Brand", allBrands:"Toate brandurile", catalog:"Catalog", nearby:"În apropiere", resetFilters:"Resetează", trustedData:"Prețuri actuale", trustedDataText:"Ofertele învechite sunt ascunse automat din comparație.", externalCheckout:"Deschidem fișa directă atunci când magazinul o oferă; broșura este marcată separat ca sursă a prețului.",
    openNow:"Deschis acum", closedNow:"Închis acum", todayHours:"astăzi", hoursUnknown:"Programul nu este specificat", onlineOnly:"Doar online", temporarilyClosed:"Închis temporar",
    account:"Contul meu", signIn:"Autentificare", signOut:"Ieșire", signInTitle:"Autentificare în Moldova Commerce", signInText:"Autentificați-vă prin OAuth pentru a păstra cardurile de fidelitate și a le folosi de pe orice dispozitiv.", continueGoogle:"Continuă cu Google", continueGithub:"Continuă cu GitHub", oauthPrivacy:"Nu stocăm parola Google sau GitHub. Autentificarea are loc la furnizorul ales.", myCards:"Cardurile mele de fidelitate", cardsIntro:"Toate cardurile magazinelor într-un singur loc — prezentați codul de bare sau QR la casă.", addCard:"Adaugă card", addCardHint:"Introduceți datele de pe cardul fizic sau din aplicația magazinului. Scanarea cu camera va fi adăugată în etapa următoare.", cardLabel:"Denumirea cardului / magazinului", cardholderName:"Numele titularului (opțional)", cardCode:"Numărul sau conținutul QR/codului de bare", cardNotes:"Notiță (opțional)", favorite:"Card favorit", saveCard:"Salvează cardul", deleteCard:"Șterge cardul", noCards:"Nu aveți încă carduri salvate.", cardSecurity:"Codul cardului este criptat înainte de salvarea în PostgreSQL. Pentru producție configurați un LOYALTY_CARD_ENCRYPTION_KEY separat.", points:"bonusuri"
  }
} as const;

type TranslationKey = keyof typeof dictionaries.ru;
export type Dictionary = Record<TranslationKey, string>;
export function getDictionary(locale: Locale): Dictionary { return dictionaries[locale]; }
export function formatMessage(template: string, values: Record<string, string | number>) { return Object.entries(values).reduce((result,[key,value])=>result.replaceAll(`{${key}}`,String(value)),template); }
export function numberLocale(locale: Locale) { return locale === "ro" ? "ro-RO" : "ru-RU"; }
export function stockLabel(status: string, quantity: number | null | undefined, locale: Locale) { const t=getDictionary(locale); if(status==="OUT_OF_STOCK"||quantity===0)return t.outOfStock; if(status==="PREORDER")return t.preorder; if(quantity!=null&&quantity>0&&quantity<=10)return formatMessage(t.inStockExact,{quantity}); if(status==="IN_STOCK"||status==="LOW_STOCK"||(quantity!=null&&quantity>10))return t.inStockLabel; return t.stockUnknown; }
const demoCategoryNames: Record<string,Record<Locale,string>>={electronics:{ru:"Электроника",ro:"Electronice"},groceries:{ru:"Продукты",ro:"Produse alimentare"},home:{ru:"Дом и быт",ro:"Casă și uz casnic"},construction:{ru:"Строительство",ro:"Construcții"},beauty:{ru:"Красота и уход",ro:"Frumusețe și îngrijire"},pets:{ru:"Зоотовары",ro:"Produse pentru animale"},baby:{ru:"Детские товары",ro:"Produse pentru copii"},produce:{ru:"Овощи и фрукты",ro:"Fructe și legume"},"meat-fish":{ru:"Мясо и рыба",ro:"Carne și pește"},dairy:{ru:"Молочные продукты",ro:"Lactate"},drinks:{ru:"Напитки",ro:"Băuturi"},alcohol:{ru:"Алкоголь",ro:"Băuturi alcoolice"},sweets:{ru:"Сладости",ro:"Dulciuri"}};
export function demoCategoryName(slug:string,locale:Locale,fallback?:string|null){return demoCategoryNames[slug]?.[locale]??fallback??slug;}
